import { StyleSheet } from 'react-native';

import { RememberCatColors, RememberCatFonts } from '@/constants/theme';

export const styles = StyleSheet.create({
  card: {
    overflow: 'hidden',
    borderRadius: 24,
    borderWidth: 1,
    borderColor: RememberCatColors.border,
    backgroundColor: RememberCatColors.card,
    padding: 16,
    shadowColor: RememberCatColors.shadow,
    shadowOpacity: 0.06,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
    elevation: 1,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
  },
  catBadge: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 16,
    backgroundColor: RememberCatColors.secondary,
    marginTop: 2,
  },
  headingCopy: { flex: 1 },
  name: {
    color: RememberCatColors.foreground,
    fontFamily: RememberCatFonts.displaySemiBold,
    fontSize: 18,
    lineHeight: 22,
  },
  summary: {
    marginTop: 2,
    color: RememberCatColors.mutedForeground,
    fontFamily: RememberCatFonts.body,
    fontSize: 12,
    lineHeight: 17,
  },
  count: {
    overflow: 'hidden',
    marginTop: 4,
    borderRadius: 999,
    backgroundColor: RememberCatColors.selectedBackground,
    paddingHorizontal: 10,
    paddingVertical: 4,
    color: RememberCatColors.primary,
    fontFamily: RememberCatFonts.bodyExtraBold,
    fontSize: 11,
    letterSpacing: 0.4,
  },
  wordList: { gap: 10, marginTop: 16 },
  wordRow: {
    minHeight: 58,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    borderRadius: 16,
    backgroundColor: RememberCatColors.muted,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  wordRowPracticed: { borderRadius: 16, backgroundColor: '#f1faf7', padding: 12 },
  wordLine: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  wordCopy: { flex: 1 },
  word: {
    color: RememberCatColors.foreground,
    fontFamily: RememberCatFonts.bodyExtraBold,
    fontSize: 14,
    lineHeight: 19,
  },
  translation: {
    marginTop: 1,
    color: RememberCatColors.mutedForeground,
    fontFamily: RememberCatFonts.body,
    fontSize: 12,
    lineHeight: 17,
  },
  unplayed: {
    overflow: 'hidden',
    borderRadius: 999,
    backgroundColor: RememberCatColors.card,
    paddingHorizontal: 10,
    paddingVertical: 5,
    color: RememberCatColors.mutedForeground,
    fontFamily: RememberCatFonts.bodyBold,
    fontSize: 10,
  },
  metricCopy: { alignItems: 'flex-end' },
  accuracy: {
    color: '#397b6d',
    fontFamily: RememberCatFonts.displaySemiBold,
    fontSize: 18,
    lineHeight: 22,
  },
  plays: {
    color: '#759087',
    fontFamily: RememberCatFonts.bodyBold,
    fontSize: 9,
    lineHeight: 13,
  },
  track: {
    height: 6,
    overflow: 'hidden',
    borderRadius: 999,
    backgroundColor: '#d8ebe5',
    marginTop: 8,
  },
  fill: { height: '100%', borderRadius: 999, backgroundColor: '#4f9f8c' },
});
