export const APP_TAB_ICON_SIZE = 15;
export const APP_TAB_ICON_CONTAINER_SIZE = 32;
export const APP_TAB_ICON_CONTAINER_RADIUS = APP_TAB_ICON_CONTAINER_SIZE / 2;
export const APP_TAB_ICON_FOCUSED_BACKGROUND_COLOR = '#fde7e3';
