import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  content: {
    flex: 1,
    paddingHorizontal: 22,
    paddingBottom: 24,
  },
  top: {
    height: 58,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  closeButton: {
    width: 36,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
  },
  close: {
    color: '#9a776c',
    fontSize: 28,
    lineHeight: 34,
  },
  progressTrack: {
    flex: 1,
    height: 9,
    overflow: 'hidden',
    borderRadius: 999,
    backgroundColor: '#eedfd6',
  },
  progressFill: {
    height: '100%',
    borderRadius: 999,
    backgroundColor: '#df8a73',
  },
  progressLabel: {
    color: '#8a665d',
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '900',
  },
  heading: {
    marginTop: 18,
  },
  kicker: {
    color: '#d17c70',
    fontSize: 11,
    lineHeight: 16,
    fontWeight: '900',
    letterSpacing: 1.2,
  },
  title: {
    color: '#50342f',
    fontSize: 30,
    lineHeight: 38,
    fontWeight: '900',
    letterSpacing: -1,
    marginTop: 5,
  },
  hint: {
    color: '#916e63',
    fontSize: 14,
    lineHeight: 21,
    marginTop: 6,
  },
  cardArea: {
    flex: 1,
    justifyContent: 'center',
    paddingVertical: 24,
  },
  card: {
    minHeight: 340,
    overflow: 'hidden',
    borderRadius: 32,
    borderWidth: 2,
    borderColor: '#f0d9ca',
    backgroundColor: '#ffffff',
    shadowColor: '#9c6255',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.14,
    shadowRadius: 20,
    elevation: 8,
  },
  cardDecoration: {
    position: 'absolute',
    top: -45,
    right: -38,
    width: 140,
    height: 140,
    borderRadius: 70,
    backgroundColor: '#fde5cd',
  },
  vocabulary: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 28,
    paddingVertical: 30,
  },
  fieldLabel: {
    color: '#c47666',
    fontSize: 11,
    lineHeight: 15,
    fontWeight: '900',
    letterSpacing: 1.5,
  },
  word: {
    color: '#4d332e',
    fontSize: 42,
    lineHeight: 52,
    fontWeight: '900',
    textAlign: 'center',
    marginTop: 8,
  },
  divider: {
    width: 54,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#7bc7b5',
    marginVertical: 24,
  },
  translation: {
    color: '#446d64',
    fontSize: 27,
    lineHeight: 36,
    fontWeight: '800',
    textAlign: 'center',
    marginTop: 8,
  },
  acknowledgeButton: {
    minHeight: 66,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 9,
    backgroundColor: '#4f9f8c',
    paddingHorizontal: 20,
    paddingVertical: 16,
  },
  acknowledgeText: {
    color: '#ffffff',
    fontSize: 17,
    lineHeight: 23,
    fontWeight: '900',
    textAlign: 'center',
  },
  acknowledgeIcon: {
    color: '#fff0d9',
    fontSize: 20,
    lineHeight: 24,
    fontWeight: '900',
  },
});
