import { StyleSheet } from 'react-native';

import { RememberCatColors, RememberCatFonts } from '@/constants/theme';

export const styles = StyleSheet.create({
  content: { flex: 1, paddingHorizontal: 20, paddingBottom: 20 },
  top: { height: 58, flexDirection: 'row', alignItems: 'center', gap: 14, zIndex: 20 },
  closeButton: {
    width: 36,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: RememberCatColors.border,
    backgroundColor: RememberCatColors.card,
  },
  closeButtonPressed: { transform: [{ scale: 0.94 }] },
  skipButton: {
    minHeight: 34,
    justifyContent: 'center',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: RememberCatColors.primaryBorder,
    backgroundColor: RememberCatColors.card,
    paddingHorizontal: 10,
  },
  skipButtonPressed: { opacity: 0.72, transform: [{ scale: 0.96 }] },
  skipButtonText: {
    color: RememberCatColors.primary,
    fontFamily: RememberCatFonts.bodyExtraBold,
    fontSize: 11,
    lineHeight: 15,
  },
  progressTrack: {
    flex: 1,
    height: 9,
    overflow: 'hidden',
    borderRadius: 999,
    backgroundColor: RememberCatColors.muted,
  },
  progressFill: {
    height: '100%',
    borderRadius: 999,
    backgroundColor: RememberCatColors.primary,
  },
  progressLabel: {
    color: RememberCatColors.mutedForeground,
    fontFamily: RememberCatFonts.bodyExtraBold,
    fontSize: 12,
    lineHeight: 16,
  },
  heading: { marginTop: 10, marginBottom: 12 },
  kicker: {
    color: RememberCatColors.primary,
    fontFamily: RememberCatFonts.bodyExtraBold,
    fontSize: 10,
    lineHeight: 14,
    letterSpacing: 1.3,
  },
  title: {
    color: RememberCatColors.foreground,
    fontFamily: RememberCatFonts.displaySemiBold,
    fontSize: 27,
    lineHeight: 34,
    marginTop: 3,
  },
  hint: {
    color: RememberCatColors.mutedForeground,
    fontFamily: RememberCatFonts.body,
    fontSize: 13,
    lineHeight: 19,
    marginTop: 3,
  },
  gridArea: {
    flex: 1,
    overflow: 'hidden',
  },
  overlay: {
    ...StyleSheet.absoluteFill,
    top: 58,
    zIndex: 10,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 14,
    paddingTop: 92,
    paddingBottom: 20,
  },
  sourceCardWrapper: { width: '100%', maxWidth: 390 },
  flyingLayer: { ...StyleSheet.absoluteFill, zIndex: 30 },
});
