import { StyleSheet } from 'react-native';

import { RememberCatColors, RememberCatFonts } from '@/constants/theme';

export const styles = StyleSheet.create({
  screen: { flex: 1, overflow: 'hidden', backgroundColor: RememberCatColors.background },
  scrollContent: {
    flexGrow: 1,
    justifyContent: 'center',
    paddingHorizontal: 24,
    paddingVertical: 32,
  },
  content: { width: '100%', maxWidth: 480, alignSelf: 'center' },
  coralOrb: {
    position: 'absolute',
    top: -105,
    right: -92,
    width: 230,
    height: 230,
    borderRadius: 115,
    backgroundColor: RememberCatColors.selectedBackground,
  },
  goldOrb: {
    position: 'absolute',
    bottom: -125,
    left: -105,
    width: 250,
    height: 250,
    borderRadius: 125,
    backgroundColor: RememberCatColors.secondary,
    opacity: 0.32,
  },
  heartDecoration: {
    position: 'absolute',
    top: '18%',
    left: '10%',
    opacity: 0.5,
    transform: [{ rotate: '-12deg' }],
  },
  sparkleDecoration: {
    position: 'absolute',
    top: '24%',
    right: '9%',
    opacity: 0.58,
    transform: [{ rotate: '9deg' }],
  },
  brandSection: { alignItems: 'center' },
  catBadge: {
    width: 104,
    height: 104,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 52,
    borderWidth: 1,
    borderColor: RememberCatColors.border,
    backgroundColor: RememberCatColors.card,
    shadowColor: RememberCatColors.shadow,
    shadowOpacity: 0.11,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 7 },
    elevation: 5,
  },
  brandRow: { flexDirection: 'row', alignItems: 'flex-end', marginTop: 16 },
  brandName: {
    color: RememberCatColors.foreground,
    fontFamily: RememberCatFonts.displaySemiBold,
    fontSize: 32,
    lineHeight: 38,
  },
  brandDot: {
    width: 7,
    height: 7,
    marginBottom: 6,
    marginLeft: 2,
    borderRadius: 4,
    backgroundColor: RememberCatColors.primary,
  },
  heroSection: { alignItems: 'center', marginTop: 38 },
  kickerPill: {
    borderRadius: 999,
    backgroundColor: RememberCatColors.selectedBackground,
    paddingHorizontal: 13,
    paddingVertical: 7,
  },
  kicker: {
    color: RememberCatColors.primary,
    fontFamily: RememberCatFonts.bodyExtraBold,
    fontSize: 10,
    lineHeight: 14,
    letterSpacing: 1.5,
  },
  title: {
    maxWidth: 330,
    marginTop: 15,
    color: RememberCatColors.foreground,
    fontFamily: RememberCatFonts.displaySemiBold,
    fontSize: 40,
    lineHeight: 47,
    textAlign: 'center',
  },
  subtitle: {
    maxWidth: 340,
    marginTop: 12,
    color: RememberCatColors.mutedForeground,
    fontFamily: RememberCatFonts.body,
    fontSize: 15,
    lineHeight: 23,
    textAlign: 'center',
  },
  actionSection: { marginTop: 42 },
  button: {
    minHeight: 60,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 20,
    backgroundColor: RememberCatColors.primary,
    shadowColor: RememberCatColors.primary,
    shadowOpacity: 0.24,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 4,
  },
  buttonPressed: { opacity: 0.9, transform: [{ scale: 0.985 }] },
  buttonText: {
    color: RememberCatColors.primaryForeground,
    fontFamily: RememberCatFonts.bodyExtraBold,
    fontSize: 17,
    lineHeight: 23,
  },
  buttonArrow: {
    position: 'absolute',
    right: 20,
    color: RememberCatColors.primaryForeground,
    fontFamily: RememberCatFonts.bodyExtraBold,
    fontSize: 22,
    lineHeight: 26,
  },
  footer: {
    marginTop: 16,
    color: RememberCatColors.mutedForeground,
    fontFamily: RememberCatFonts.bodyBold,
    fontSize: 11,
    lineHeight: 16,
    textAlign: 'center',
  },
});
