import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#fff8f1', overflow: 'hidden' },
  safeArea: {
    flex: 1,
    paddingHorizontal: 28,
    paddingVertical: 16,
    justifyContent: 'space-between',
  },
  blobTop: {
    position: 'absolute',
    top: -160,
    right: -100,
    width: 380,
    height: 380,
    borderRadius: 190,
    backgroundColor: '#ffd8b6',
    opacity: 0.72,
  },
  blobBottom: {
    position: 'absolute',
    bottom: -170,
    left: -110,
    width: 340,
    height: 340,
    borderRadius: 170,
    backgroundColor: '#f7c6c7',
    opacity: 0.46,
  },
  heartLeft: { left: '12%', top: '24%' },
  heartRight: { right: '13%', top: '17%' },
  eyebrow: {
    alignSelf: 'center',
    borderRadius: 20,
    backgroundColor: '#fff',
    paddingHorizontal: 12,
    paddingVertical: 7,
    color: '#8b6255',
    fontSize: 10,
    letterSpacing: 1.3,
    fontWeight: '800',
  },
  hero: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  title: {
    textAlign: 'center',
    fontSize: 47,
    lineHeight: 52,
    letterSpacing: -2.2,
    fontWeight: '800',
    color: '#4b302d',
  },
  titleAccent: { color: '#dc8075' },
  subtitle: {
    maxWidth: 310,
    textAlign: 'center',
    fontSize: 16,
    lineHeight: 24,
    color: '#87655d',
    marginTop: 17,
  },
  button: {
    height: 62,
    borderRadius: 21,
    backgroundColor: '#4c302e',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#4c302e',
    shadowOpacity: 0.28,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 6,
  },
  buttonText: { color: '#fffaf3', fontSize: 17, fontWeight: '800' },
  footer: {
    textAlign: 'center',
    color: '#a4887d',
    fontSize: 11,
    marginTop: 15,
  },
});
