import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#fff8f1', paddingHorizontal: 22 },
  content: { flex: 1 },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 13,
    paddingTop: 8,
  },
  back: { fontSize: 40, lineHeight: 38, color: '#51342f' },
  kicker: {
    color: '#d77c70',
    fontWeight: '800',
    letterSpacing: 1.3,
    fontSize: 10,
  },
  title: {
    color: '#51342f',
    fontSize: 27,
    fontWeight: '800',
    letterSpacing: -0.8,
  },
  intro: { color: '#87675d', fontSize: 14, lineHeight: 21, marginTop: 22 },
  currentDeckHeading: { marginTop: 25 },
  currentDeckTitle: { color: '#51342f', fontSize: 19, lineHeight: 25, fontWeight: '900' },
  currentDeckHint: { color: '#96756a', fontSize: 12, lineHeight: 18, marginTop: 3 },
  count: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginTop: 12,
    marginBottom: 12,
  },
  countText: { color: '#9a786d', fontSize: 12, fontWeight: '800' },
  track: {
    height: 7,
    flex: 1,
    borderRadius: 5,
    backgroundColor: '#f1ddd2',
    overflow: 'hidden',
  },
  fill: { height: '100%', backgroundColor: '#d98072', borderRadius: 5 },
  list: { flex: 1 },
  listContent: { paddingBottom: 12, flexGrow: 1 },
  pairGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', gap: 8 },
  empty: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingBottom: 40,
  },
  emptyIcon: { color: '#e39a87', fontSize: 43 },
  emptyTitle: {
    color: '#5a3933',
    fontSize: 20,
    fontWeight: '800',
    marginTop: 10,
  },
  emptyCopy: { color: '#9c7e73', fontSize: 13, marginTop: 6 },
  pairCard: {
    width: '48.5%',
    backgroundColor: '#fff',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#f0ddd1',
    padding: 10,
    marginBottom: 2,
  },
  pairHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 3,
  },
  pairNumber: {
    color: '#b0887c',
    fontSize: 9,
    fontWeight: '800',
    letterSpacing: 0.9,
  },
  remove: { color: '#d87870', fontSize: 9, fontWeight: '700' },
  input: {
    height: 38,
    borderRadius: 12,
    backgroundColor: '#fff8f2',
    borderWidth: 1,
    borderColor: '#f0ddd1',
    paddingHorizontal: 8,
    color: '#553832',
    fontSize: 12,
    marginTop: 5,
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(67, 39, 34, 0.35)',
    justifyContent: 'center',
    paddingHorizontal: 22,
  },
  modalCard: {
    backgroundColor: '#fff8f1',
    borderRadius: 28,
    padding: 24,
    shadowColor: '#452a25',
    shadowOpacity: 0.22,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 9,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  modalTitle: {
    color: '#51342f',
    fontSize: 25,
    fontWeight: '800',
    letterSpacing: -0.7,
    marginTop: 3,
  },
  close: { color: '#9b796e', fontSize: 29 },
  modalCopy: {
    color: '#8b6a60',
    fontSize: 14,
    lineHeight: 20,
    marginTop: 14,
    marginBottom: 14,
  },
  modalInput: {
    height: 52,
    borderRadius: 14,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#ecd9ce',
    paddingHorizontal: 14,
    color: '#51342f',
    fontSize: 15,
    marginTop: 9,
  },
  bulkInput: {
    minHeight: 150,
    borderRadius: 14,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#ecd9ce',
    padding: 14,
    color: '#51342f',
    fontSize: 15,
    marginTop: 9,
  },
  saveButton: {
    height: 57,
    borderRadius: 18,
    backgroundColor: '#51342f',
    marginTop: 17,
    alignItems: 'center',
    justifyContent: 'center',
  },
  saveButtonDisabled: { backgroundColor: '#cdb8ae' },
  saveText: { color: '#fff', fontWeight: '800', fontSize: 16 },
  saveArrow: {
    position: 'absolute',
    right: 19,
    color: '#f3bd9f',
    fontSize: 22,
  },
});
