import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  card: {
    minHeight: 92,
    borderRadius: 20,
    padding: 16,
    backgroundColor: '#ffead7',
    borderWidth: 1,
    borderColor: '#f0c9ad',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    gap: 12,
    shadowColor: '#9c6e5d',
    shadowOpacity: 0.06,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
    elevation: 1,
  },
  icon: {
    width: 43,
    height: 43,
    borderRadius: 15,
    backgroundColor: '#e78c79',
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconText: { color: '#fff', fontSize: 19 },
  copy: { flex: 1 },
  title: { color: '#563832', fontSize: 16, fontWeight: '800' },
  detail: { color: '#96756a', fontSize: 12, marginTop: 4 },
  chevron: { color: '#bc745e', fontSize: 31, lineHeight: 32 },
  status: {
    minHeight: 92,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 20,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: '#e3cfc4',
    backgroundColor: '#fffdf9',
    paddingHorizontal: 18,
  },
  statusText: {
    color: '#a1847a',
    fontSize: 12,
    lineHeight: 18,
    textAlign: 'center',
  },
  continueActions: { paddingTop: 2, paddingBottom: 12 },
  continueHint: {
    color: '#a2877d',
    textAlign: 'center',
    fontSize: 12,
    marginBottom: 12,
  },
  continueButton: {
    height: 60,
    borderRadius: 19,
    backgroundColor: '#51342f',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#51342f',
    shadowOpacity: 0.22,
    shadowRadius: 9,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  continueText: { color: '#fff', fontSize: 16, fontWeight: '800' },
  continueArrow: {
    color: '#f3bd9f',
    fontSize: 22,
    position: 'absolute',
    right: 19,
  },
});
