import { PREPARATION_WORD_TILE_HEIGHT } from '../PreparationWordTile/constants';

export const PREPARATION_GRID_COLUMN_COUNT = 3;
export const PREPARATION_GRID_GAP = 8;
export const PREPARATION_GRID_PADDING = 12;
export const PREPARATION_GRID_ROW_HEIGHT = PREPARATION_WORD_TILE_HEIGHT + PREPARATION_GRID_GAP;
export const PREPARATION_GRID_SCROLL_LEAD = PREPARATION_GRID_ROW_HEIGHT;
