import { StyleSheet } from 'react-native';
export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#fff8f1', paddingHorizontal: 20 },
  top: { height: 58, flexDirection: 'row', alignItems: 'center', gap: 12 },
  close: { fontSize: 30, color: '#9a776c' },
  track: { flex: 1, height: 10, backgroundColor: '#f0ddd1', borderRadius: 9, overflow: 'hidden' },
  fill: { height: '100%', backgroundColor: '#d98072', borderRadius: 9 },
  score: { color: '#9a776c', fontWeight: '800', fontSize: 12 },
  heading: { marginTop: 18, marginBottom: 20 },
  kicker: { color: '#d17c70', fontWeight: '800', letterSpacing: 1.1, fontSize: 11 },
  title: { color: '#50342f', fontWeight: '800', fontSize: 30, letterSpacing: -1.1, marginTop: 5 },
  hint: { color: '#916e63', fontSize: 14, marginTop: 6 },
  board: { flexDirection: 'row', gap: 11, flex: 1, alignItems: 'center' },
  column: { flex: 1, gap: 10 },
  card: {
    height: 58,
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: '#efdcd0',
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
  },
  selected: { backgroundColor: '#f4d1b5', borderColor: '#df8a73' },
  correct: { backgroundColor: '#d8f4d8', borderColor: '#55a966' },
  incorrect: { backgroundColor: '#ffdedb', borderColor: '#e35b59' },
  cardText: { fontSize: 14, color: '#5d4038', fontWeight: '700' },
  result: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 28,
    backgroundColor: '#fff8f1',
  },
  resultTitle: { color: '#50342f', fontWeight: '800', fontSize: 36 },
  resultCopy: { color: '#8e6d63', textAlign: 'center', fontSize: 16, marginTop: 12 },
  resultButton: {
    marginTop: 28,
    borderRadius: 18,
    backgroundColor: '#50342f',
    paddingHorizontal: 25,
    paddingVertical: 16,
  },
  resultButtonText: { color: '#fff', fontWeight: '800' },
});
