import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#fff8f1', paddingHorizontal: 22 },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 13,
    paddingTop: 8,
  },
  back: { fontSize: 40, lineHeight: 38, color: '#51342f' },
  kicker: {
    color: '#d77c70',
    fontWeight: '800',
    letterSpacing: 1.3,
    fontSize: 10,
  },
  title: {
    color: '#51342f',
    fontSize: 27,
    fontWeight: '800',
    letterSpacing: -0.8,
  },
  intro: {
    color: '#87675d',
    fontSize: 15,
    lineHeight: 22,
    marginTop: 25,
    maxWidth: 320,
  },
  cards: { gap: 12, marginTop: 28 },
  card: {
    minHeight: 92,
    borderRadius: 20,
    padding: 16,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#f0ddd1',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    shadowColor: '#9c6e5d',
    shadowOpacity: 0.06,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
    elevation: 1,
  },
  cardTitle: { color: '#563832', fontSize: 16, fontWeight: '800' },
  cardDetail: { color: '#96756a', fontSize: 12, marginTop: 4 },
  toggle: {
    backgroundColor: '#f8e4d4',
    padding: 3,
    borderRadius: 13,
    flexDirection: 'row',
  },
  toggleOption: { paddingHorizontal: 10, paddingVertical: 8, borderRadius: 10 },
  toggleSelected: { backgroundColor: '#573733' },
  toggleText: { color: '#916d61', fontWeight: '800', fontSize: 11 },
  toggleTextSelected: { color: '#fff' },
  wordsCard: {
    backgroundColor: '#ffead7',
    borderColor: '#f0c9ad',
    justifyContent: 'flex-start',
    gap: 12,
  },
  wordsIcon: {
    width: 43,
    height: 43,
    borderRadius: 15,
    backgroundColor: '#e78c79',
    alignItems: 'center',
    justifyContent: 'center',
  },
  wordsIconText: { color: '#fff', fontSize: 19 },
  wordsCopy: { flex: 1 },
  chevron: { color: '#bc745e', fontSize: 31, lineHeight: 32 },
  footer: { marginTop: 'auto', paddingBottom: 12 },
  footerHint: {
    color: '#a2877d',
    textAlign: 'center',
    fontSize: 12,
    marginBottom: 12,
  },
  startButton: {
    height: 60,
    borderRadius: 19,
    backgroundColor: '#51342f',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#51342f',
    shadowOpacity: 0.22,
    shadowRadius: 9,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  startButtonDisabled: { backgroundColor: '#cdb8ae', shadowOpacity: 0 },
  startText: { color: '#fff', fontSize: 16, fontWeight: '800' },
  startArrow: {
    color: '#f3bd9f',
    fontSize: 22,
    position: 'absolute',
    right: 19,
  },
});
