import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    overflow: 'hidden',
    backgroundColor: '#dff4ef',
  },
  decorations: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
  },
  topBubble: {
    position: 'absolute',
    top: -86,
    right: -58,
    width: 230,
    height: 230,
    borderRadius: 115,
    backgroundColor: 'rgba(79, 173, 151, 0.16)',
  },
  bottomBubble: {
    position: 'absolute',
    bottom: -104,
    left: -72,
    width: 270,
    height: 270,
    borderRadius: 135,
    backgroundColor: 'rgba(255, 183, 112, 0.2)',
  },
  leftSparkle: {
    position: 'absolute',
    top: '18%',
    left: 34,
    color: '#f0a45d',
    fontSize: 34,
    lineHeight: 42,
  },
  rightSparkle: {
    position: 'absolute',
    top: '24%',
    right: 36,
    color: '#4fad97',
    fontSize: 28,
    lineHeight: 36,
  },
  content: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
    paddingVertical: 30,
  },
  levelPill: {
    borderRadius: 999,
    paddingHorizontal: 16,
    paddingVertical: 8,
    backgroundColor: '#4fad97',
  },
  levelText: {
    color: '#ffffff',
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '900',
    letterSpacing: 1.5,
  },
  catStage: {
    width: 220,
    height: 220,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 22,
  },
  catGlow: {
    position: 'absolute',
    width: 196,
    height: 196,
    borderRadius: 98,
    backgroundColor: '#fffaf4',
    borderWidth: 5,
    borderColor: '#8bd1c1',
    shadowColor: '#277d69',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.2,
    shadowRadius: 18,
    elevation: 8,
  },
  cat: {
    fontSize: 112,
    lineHeight: 132,
  },
  pawTrail: {
    position: 'absolute',
    bottom: -4,
    color: '#d98259',
    fontSize: 24,
    lineHeight: 32,
  },
  copy: {
    width: '100%',
    maxWidth: 390,
    alignItems: 'center',
    marginTop: 22,
  },
  title: {
    color: '#3f4d48',
    fontSize: 36,
    lineHeight: 44,
    fontWeight: '900',
    letterSpacing: -1,
    textAlign: 'center',
  },
  message: {
    color: '#687d76',
    fontSize: 16,
    lineHeight: 24,
    textAlign: 'center',
    marginTop: 10,
  },
  button: {
    minHeight: 58,
    width: '100%',
    maxWidth: 370,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    marginTop: 32,
    borderRadius: 20,
    paddingHorizontal: 22,
    paddingVertical: 15,
    backgroundColor: '#3f4d48',
    shadowColor: '#24433b',
    shadowOffset: { width: 0, height: 7 },
    shadowOpacity: 0.22,
    shadowRadius: 12,
    elevation: 6,
  },
  buttonText: {
    color: '#ffffff',
    fontSize: 17,
    lineHeight: 23,
    fontWeight: '900',
  },
  buttonIcon: {
    color: '#ffd29f',
    fontSize: 22,
    lineHeight: 28,
    fontWeight: '900',
  },
});
