import { StyleSheet } from 'react-native';

import { RememberCatColors, RememberCatFonts } from '@/constants/theme';

export const styles = StyleSheet.create({
  card: {
    minHeight: 330,
    overflow: 'hidden',
    borderRadius: 30,
    borderWidth: 2,
    borderColor: RememberCatColors.border,
    backgroundColor: RememberCatColors.card,
    shadowColor: RememberCatColors.shadow,
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.18,
    shadowRadius: 20,
    elevation: 10,
  },
  cardDecoration: {
    position: 'absolute',
    top: -45,
    right: -38,
    width: 140,
    height: 140,
    borderRadius: 70,
    backgroundColor: RememberCatColors.selectedBackground,
  },
  vocabulary: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 28,
    paddingVertical: 28,
  },
  fieldLabel: {
    color: RememberCatColors.primary,
    fontFamily: RememberCatFonts.bodyExtraBold,
    fontSize: 10,
    lineHeight: 14,
    letterSpacing: 1.5,
  },
  word: {
    color: RememberCatColors.foreground,
    fontFamily: RememberCatFonts.displaySemiBold,
    fontSize: 39,
    lineHeight: 48,
    textAlign: 'center',
    marginTop: 6,
  },
  divider: {
    width: 52,
    height: 4,
    borderRadius: 2,
    backgroundColor: RememberCatColors.secondary,
    marginVertical: 20,
  },
  translation: {
    color: RememberCatColors.success,
    fontFamily: RememberCatFonts.displaySemiBold,
    fontSize: 25,
    lineHeight: 33,
    textAlign: 'center',
    marginTop: 6,
  },
  acknowledgeButton: {
    minHeight: 62,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 9,
    backgroundColor: RememberCatColors.primary,
    paddingHorizontal: 20,
    paddingVertical: 14,
  },
  acknowledgeButtonPressed: { opacity: 0.9 },
  acknowledgeText: {
    color: RememberCatColors.primaryForeground,
    fontFamily: RememberCatFonts.bodyExtraBold,
    fontSize: 16,
    lineHeight: 22,
    textAlign: 'center',
  },
  acknowledgeIcon: {
    color: RememberCatColors.primaryForeground,
    fontFamily: RememberCatFonts.bodyExtraBold,
    fontSize: 19,
    lineHeight: 23,
  },
});
