export const MATCH_OPTION_ACCESSIBILITY_LABEL_PREFIX = 'Match option:';
export const CARD_ENTER_SCALE = 0.78;
export const CARD_SELECTED_SCALE = 1.045;
export const CORRECT_CARD_HOLD_DURATION_MS = 300;
export const INCORRECT_CARD_SHAKE_DISTANCE = 5;
export const INCORRECT_CARD_SHAKE_DURATION_MS = 60;
