import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  wrapper: {
    height: 58,
    zIndex: 1,
  },
  feedbackWrapper: {
    zIndex: 10,
    elevation: 10,
  },
  card: {
    flex: 1,
    backfaceVisibility: 'hidden',
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: '#efdcd0',
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
  },
  selected: {
    backgroundColor: '#f4d1b5',
    borderColor: '#df8a73',
    shadowColor: '#b86252',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 4,
  },
  correct: {
    backgroundColor: '#d8f4d8',
    borderColor: '#55a966',
  },
  shatterCorrect: {
    backgroundColor: '#ffe2c8',
    borderColor: '#ee7b59',
  },
  portalCorrect: {
    backgroundColor: '#ebe4ff',
    borderColor: '#8b6ee8',
  },
  completed: {
    borderColor: '#b9cbbd',
    backgroundColor: '#edf3ed',
    paddingRight: 36,
  },
  completedTransitionGlow: {
    position: 'absolute',
    top: -1.5,
    right: -1.5,
    bottom: -1.5,
    left: -1.5,
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: '#55a966',
    backgroundColor: '#d8f4d8',
  },
  completedText: {
    color: '#708075',
  },
  completedMarkBadge: {
    position: 'absolute',
    top: 16,
    right: 8,
    width: 25,
    height: 25,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: '#75a980',
    backgroundColor: '#d8ecdc',
  },
  completedMark: {
    color: '#4f8b5d',
    fontSize: 15,
    lineHeight: 18,
    fontWeight: '900',
  },
  countdownBadge: {
    position: 'absolute',
    zIndex: 8,
    top: -16,
    right: -7,
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 3,
    borderColor: '#fff8ec',
    backgroundColor: '#dc725f',
    shadowColor: '#8d392d',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.3,
    shadowRadius: 7,
    elevation: 8,
  },
  countdownNumber: {
    color: '#fff',
    fontSize: 22,
    lineHeight: 27,
    fontWeight: '900',
  },
  countdownSparkLeft: {
    position: 'absolute',
    top: -12,
    left: -11,
    color: '#f2b24d',
    fontSize: 17,
    lineHeight: 20,
    fontWeight: '900',
  },
  countdownSparkRight: {
    position: 'absolute',
    right: -12,
    bottom: -9,
    color: '#f4cb69',
    fontSize: 15,
    lineHeight: 18,
    fontWeight: '900',
  },
  celebrationLayer: {
    position: 'absolute',
    zIndex: 12,
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    alignItems: 'center',
    justifyContent: 'center',
  },
  shatterFragment: {
    position: 'absolute',
    width: 18,
    height: 12,
    borderRadius: 3,
    borderWidth: 1,
    borderColor: '#fff0dc',
    backgroundColor: '#ef805c',
  },
  shatterFragmentGold: {
    backgroundColor: '#f2b449',
  },
  shatterFragmentPink: {
    backgroundColor: '#df6685',
  },
  shatterFragmentOne: {
    top: 8,
    left: '42%',
  },
  shatterFragmentTwo: {
    bottom: 9,
    left: '31%',
  },
  shatterFragmentThree: {
    top: 12,
    right: '29%',
  },
  shatterFragmentFour: {
    right: '42%',
    bottom: 8,
  },
  shatterLabelContainer: {
    position: 'absolute',
    top: -19,
    right: 0,
    left: 0,
    alignItems: 'center',
  },
  shatterLabel: {
    color: '#b94235',
    fontSize: 16,
    lineHeight: 20,
    fontWeight: '900',
    letterSpacing: 0.8,
    textShadowColor: '#fff4d8',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 1,
  },
  portalOuterRing: {
    position: 'absolute',
    width: 116,
    height: 50,
    borderRadius: 30,
    borderWidth: 4,
    borderColor: '#855de8',
    backgroundColor: 'rgba(99, 62, 190, 0.08)',
  },
  portalInnerRing: {
    position: 'absolute',
    width: 88,
    height: 36,
    borderRadius: 22,
    borderWidth: 3,
    borderColor: '#54d6dc',
    backgroundColor: 'rgba(84, 214, 220, 0.12)',
  },
  portalCore: {
    position: 'absolute',
    width: 42,
    height: 18,
    borderRadius: 12,
    backgroundColor: '#4d318f',
  },
  portalSparkContainer: {
    position: 'absolute',
  },
  portalSpark: {
    color: '#f2c85b',
    fontSize: 23,
    lineHeight: 27,
    fontWeight: '900',
  },
  portalSparkLeft: {
    top: -13,
    left: 20,
  },
  portalSparkRight: {
    right: 18,
    bottom: -12,
  },
  burstRing: {
    position: 'absolute',
    top: 4,
    right: 12,
    bottom: 4,
    left: 12,
    borderRadius: 22,
    borderWidth: 3,
    borderColor: '#69c27b',
    backgroundColor: 'rgba(105, 194, 123, 0.12)',
  },
  burstSpark: {
    position: 'absolute',
    top: -18,
    right: -3,
    color: '#e5a24e',
    fontSize: 26,
    lineHeight: 30,
    fontWeight: '900',
  },
  incorrect: {
    backgroundColor: '#ffdedb',
    borderColor: '#e35b59',
  },
  text: {
    zIndex: 1,
    fontSize: 14,
    lineHeight: 20,
    color: '#5d4038',
    fontWeight: '700',
  },
});
