import { StyleSheet } from 'react-native';

import { RememberCatColors, RememberCatFonts } from '@/constants/theme';

export const styles = StyleSheet.create({
  card: {
    overflow: 'hidden',
    borderRadius: 24,
    borderWidth: 1,
    borderColor: RememberCatColors.border,
    backgroundColor: RememberCatColors.card,
    shadowColor: RememberCatColors.shadow,
    shadowOpacity: 0.06,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
    elevation: 1,
  },
  cardSelected: {
    borderColor: RememberCatColors.primaryBorder,
    shadowColor: RememberCatColors.primary,
    shadowOpacity: 0.22,
    shadowRadius: 0,
    shadowOffset: { width: 0, height: 0 },
    elevation: 2,
  },
  selectButton: { flexDirection: 'row', alignItems: 'flex-start', gap: 12, padding: 16 },
  pressed: { transform: [{ scale: 0.97 }], opacity: 0.92 },
  catBadge: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 16,
    backgroundColor: RememberCatColors.secondary,
    marginTop: 2,
  },
  catBadgeSelected: { backgroundColor: RememberCatColors.primary },
  headingCopy: { flex: 1 },
  name: {
    color: RememberCatColors.foreground,
    fontFamily: RememberCatFonts.displaySemiBold,
    fontSize: 18,
    lineHeight: 22,
  },
  count: {
    marginTop: 2,
    color: RememberCatColors.mutedForeground,
    fontFamily: RememberCatFonts.body,
    fontSize: 14,
    lineHeight: 19,
  },
  selectedBadge: {
    overflow: 'hidden',
    marginTop: 4,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
    backgroundColor: RememberCatColors.selectedBackground,
    color: RememberCatColors.primary,
    fontFamily: RememberCatFonts.bodyExtraBold,
    fontSize: 11,
    letterSpacing: 0.4,
  },
  actions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 16,
    paddingBottom: 12,
  },
  actionButton: {
    minHeight: 30,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderRadius: 999,
    backgroundColor: RememberCatColors.muted,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  deleteButton: {
    minHeight: 30,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderRadius: 999,
    backgroundColor: RememberCatColors.destructiveBackground,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  actionText: {
    color: RememberCatColors.foreground,
    fontFamily: RememberCatFonts.bodyBold,
    fontSize: 13,
  },
  deleteText: {
    color: RememberCatColors.destructive,
    fontFamily: RememberCatFonts.bodyBold,
    fontSize: 13,
  },
  previewButton: {
    marginLeft: 'auto',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  previewText: {
    color: RememberCatColors.mutedForeground,
    fontFamily: RememberCatFonts.bodyBold,
    fontSize: 13,
  },
  chevronExpanded: { transform: [{ rotate: '180deg' }] },
  wordList: {
    borderTopWidth: 1,
    borderTopColor: RememberCatColors.border,
    paddingHorizontal: 16,
    paddingVertical: 8,
  },
  wordRow: {
    minHeight: 40,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: RememberCatColors.border,
    paddingVertical: 8,
  },
  wordNumber: {
    width: 24,
    height: 24,
    overflow: 'hidden',
    borderRadius: 12,
    backgroundColor: RememberCatColors.muted,
    color: RememberCatColors.mutedForeground,
    fontFamily: RememberCatFonts.bodyExtraBold,
    fontSize: 11,
    lineHeight: 24,
    textAlign: 'center',
  },
  word: {
    flex: 1,
    color: RememberCatColors.foreground,
    fontFamily: RememberCatFonts.bodyBold,
    fontSize: 15,
  },
  translation: {
    flex: 1,
    color: RememberCatColors.mutedForeground,
    fontFamily: RememberCatFonts.body,
    fontSize: 15,
    textAlign: 'right',
  },
});
