import { StyleSheet } from 'react-native';

import { RememberCatColors, RememberCatFonts } from '@/constants/theme';

export const styles = StyleSheet.create({
  card: {
    position: 'absolute',
    overflow: 'hidden',
    borderWidth: 1.5,
    borderColor: RememberCatColors.primaryBorder,
    backgroundColor: RememberCatColors.card,
    shadowColor: RememberCatColors.shadow,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.18,
    shadowRadius: 14,
    elevation: 12,
  },
  detailedContent: { ...StyleSheet.absoluteFill },
  decoration: {
    position: 'absolute',
    top: -45,
    right: -38,
    width: 140,
    height: 140,
    borderRadius: 70,
    backgroundColor: RememberCatColors.selectedBackground,
  },
  vocabulary: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 28,
    paddingBottom: 62,
  },
  fieldLabel: {
    color: RememberCatColors.primary,
    fontFamily: RememberCatFonts.bodyExtraBold,
    fontSize: 10,
    lineHeight: 14,
    letterSpacing: 1.4,
  },
  largeWord: {
    color: RememberCatColors.foreground,
    fontFamily: RememberCatFonts.displaySemiBold,
    fontSize: 37,
    lineHeight: 45,
    textAlign: 'center',
    marginTop: 5,
  },
  largeDivider: {
    width: 50,
    height: 4,
    marginVertical: 16,
    borderRadius: 2,
    backgroundColor: RememberCatColors.secondary,
  },
  largeTranslation: {
    color: RememberCatColors.success,
    fontFamily: RememberCatFonts.displaySemiBold,
    fontSize: 24,
    lineHeight: 31,
    textAlign: 'center',
    marginTop: 5,
  },
  buttonPreview: {
    position: 'absolute',
    right: 0,
    bottom: 0,
    left: 0,
    height: 62,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: RememberCatColors.primary,
  },
  buttonPreviewText: {
    color: RememberCatColors.primaryForeground,
    fontFamily: RememberCatFonts.bodyExtraBold,
    fontSize: 15,
  },
  compactContent: {
    ...StyleSheet.absoluteFill,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 7,
  },
  compactWord: {
    width: '100%',
    color: RememberCatColors.foreground,
    fontFamily: RememberCatFonts.displaySemiBold,
    fontSize: 14,
    lineHeight: 17,
    textAlign: 'center',
  },
  compactDivider: {
    width: 20,
    height: 2,
    marginVertical: 5,
    borderRadius: 1,
    backgroundColor: RememberCatColors.secondary,
  },
  compactTranslation: {
    width: '100%',
    color: RememberCatColors.success,
    fontFamily: RememberCatFonts.bodyBold,
    fontSize: 11,
    lineHeight: 14,
    textAlign: 'center',
  },
});
