import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    overflow: 'hidden',
    backgroundColor: '#5b3432',
  },
  content: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 26,
    paddingVertical: 32,
  },
  decorations: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
  },
  leftBolt: {
    position: 'absolute',
    top: '20%',
    left: 32,
    color: '#ffbd59',
    fontSize: 46,
    lineHeight: 54,
    transform: [{ rotate: '-12deg' }],
  },
  rightBolt: {
    position: 'absolute',
    top: '14%',
    right: 36,
    color: '#ff8f5e',
    fontSize: 36,
    lineHeight: 44,
    transform: [{ rotate: '14deg' }],
  },
  topOrb: {
    position: 'absolute',
    top: -90,
    left: -60,
    width: 230,
    height: 230,
    borderRadius: 115,
    backgroundColor: 'rgba(255, 143, 94, 0.13)',
  },
  bottomOrb: {
    position: 'absolute',
    right: -80,
    bottom: -110,
    width: 280,
    height: 280,
    borderRadius: 140,
    backgroundColor: 'rgba(255, 189, 89, 0.1)',
  },
  catStage: {
    width: 210,
    height: 210,
    alignItems: 'center',
    justifyContent: 'center',
  },
  catGlow: {
    position: 'absolute',
    width: 190,
    height: 190,
    borderRadius: 95,
    backgroundColor: '#fff2df',
    borderWidth: 5,
    borderColor: '#ff9c68',
    shadowColor: '#ff8f5e',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.45,
    shadowRadius: 22,
    elevation: 9,
  },
  cat: {
    fontSize: 112,
    lineHeight: 132,
  },
  copy: {
    width: '100%',
    maxWidth: 390,
    alignItems: 'center',
    marginTop: 22,
  },
  title: {
    color: '#fff5e9',
    fontWeight: '900',
    fontSize: 34,
    lineHeight: 42,
    letterSpacing: 0.3,
    textAlign: 'center',
  },
  message: {
    color: '#f3cbb8',
    fontSize: 16,
    lineHeight: 24,
    textAlign: 'center',
    marginTop: 12,
  },
  button: {
    minHeight: 58,
    width: '100%',
    maxWidth: 370,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    marginTop: 34,
    borderRadius: 20,
    paddingHorizontal: 22,
    paddingVertical: 15,
    backgroundColor: '#ffbd59',
    shadowColor: '#160d0c',
    shadowOffset: { width: 0, height: 7 },
    shadowOpacity: 0.28,
    shadowRadius: 12,
    elevation: 6,
  },
  buttonText: {
    color: '#50342f',
    fontWeight: '900',
    fontSize: 17,
    lineHeight: 23,
  },
  buttonIcon: {
    fontSize: 21,
    lineHeight: 27,
  },
});
