import { StyleSheet } from 'react-native';

import { RememberCatColors, RememberCatFonts } from '@/constants/theme';

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: RememberCatColors.background },
  scroll: { flex: 1 },
  scrollContent: { flexGrow: 1, paddingHorizontal: 20, paddingTop: 20, paddingBottom: 24 },
  header: { paddingBottom: 4 },
  headerTop: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  headerButton: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 22,
    borderWidth: 1,
    borderColor: RememberCatColors.border,
    backgroundColor: RememberCatColors.card,
    elevation: 2,
  },
  pressed: { transform: [{ scale: 0.95 }] },
  brandBadge: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 22,
    backgroundColor: RememberCatColors.selectedBackground,
  },
  kicker: {
    marginTop: 24,
    color: RememberCatColors.primary,
    fontFamily: RememberCatFonts.bodyExtraBold,
    fontSize: 12,
    lineHeight: 16,
    letterSpacing: 2.16,
    textTransform: 'uppercase',
  },
  title: {
    marginTop: 6,
    color: RememberCatColors.foreground,
    fontFamily: RememberCatFonts.displaySemiBold,
    fontSize: 32,
    lineHeight: 38,
  },
  intro: {
    marginTop: 8,
    color: RememberCatColors.mutedForeground,
    fontFamily: RememberCatFonts.body,
    fontSize: 15,
    lineHeight: 24,
  },
  selectorSection: { marginTop: 20 },
  selectorLabel: {
    marginBottom: 8,
    paddingHorizontal: 4,
    color: RememberCatColors.foreground,
    fontFamily: RememberCatFonts.bodyBold,
    fontSize: 14,
  },
  library: { marginTop: 20 },
  listSections: { gap: 16 },
  statusText: {
    paddingHorizontal: 4,
    paddingVertical: 12,
    color: RememberCatColors.mutedForeground,
    fontFamily: RememberCatFonts.body,
    fontSize: 14,
  },
  emptyState: {
    alignItems: 'center',
    borderRadius: 24,
    borderWidth: 1,
    borderColor: RememberCatColors.border,
    backgroundColor: RememberCatColors.card,
    padding: 32,
  },
  emptyCat: {
    width: 80,
    height: 80,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 40,
    backgroundColor: RememberCatColors.secondary,
  },
  emptyTitle: {
    marginTop: 16,
    color: RememberCatColors.foreground,
    fontFamily: RememberCatFonts.displaySemiBold,
    fontSize: 20,
  },
  emptyMessage: {
    marginTop: 6,
    color: RememberCatColors.mutedForeground,
    fontFamily: RememberCatFonts.body,
    fontSize: 14,
    lineHeight: 21,
    textAlign: 'center',
  },
  createButton: {
    minHeight: 50,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: RememberCatColors.border,
    backgroundColor: RememberCatColors.card,
    marginTop: 16,
  },
  createText: {
    color: RememberCatColors.primary,
    fontFamily: RememberCatFonts.bodyExtraBold,
    fontSize: 14,
  },
  startBar: {
    borderTopWidth: 1,
    borderTopColor: RememberCatColors.border,
    backgroundColor: RememberCatColors.card,
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 12,
  },
  startButton: {
    height: 56,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 24,
    backgroundColor: RememberCatColors.primary,
    elevation: 3,
  },
  startText: {
    color: RememberCatColors.primaryForeground,
    fontFamily: RememberCatFonts.bodyExtraBold,
    fontSize: 16,
  },
});
