import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    overflow: 'hidden',
    backgroundColor: '#ffe8db',
  },
  content: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
    paddingVertical: 28,
  },
  decorations: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
  },
  topSparkle: {
    position: 'absolute',
    top: '9%',
    alignSelf: 'center',
    color: '#d98072',
    fontSize: 30,
    lineHeight: 38,
  },
  leftSparkle: {
    position: 'absolute',
    top: '25%',
    left: 30,
    color: '#e7a18e',
    fontSize: 26,
    lineHeight: 34,
  },
  rightSparkle: {
    position: 'absolute',
    top: '18%',
    right: 32,
    color: '#e7a18e',
    fontSize: 22,
    lineHeight: 30,
  },
  leftCloud: {
    position: 'absolute',
    bottom: 88,
    left: -42,
    width: 132,
    height: 72,
    borderRadius: 50,
    backgroundColor: 'rgba(255,255,255,0.48)',
  },
  rightCloud: {
    position: 'absolute',
    top: 120,
    right: -58,
    width: 148,
    height: 82,
    borderRadius: 55,
    backgroundColor: 'rgba(255,255,255,0.4)',
  },
  catStage: {
    width: 202,
    height: 202,
    alignItems: 'center',
    justifyContent: 'center',
  },
  catGlow: {
    position: 'absolute',
    width: 184,
    height: 184,
    borderRadius: 92,
    backgroundColor: '#fff8f1',
    borderWidth: 4,
    borderColor: '#f8cbbb',
    shadowColor: '#8a5849',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.16,
    shadowRadius: 18,
    elevation: 7,
  },
  cat: {
    fontSize: 108,
    lineHeight: 126,
  },
  celebrationPaws: {
    position: 'absolute',
    bottom: -2,
    color: '#c56f64',
    fontSize: 24,
    lineHeight: 32,
  },
  storyCard: {
    width: '100%',
    maxWidth: 390,
    alignItems: 'center',
    marginTop: 24,
    paddingHorizontal: 22,
  },
  title: {
    color: '#50342f',
    fontWeight: '900',
    fontSize: 34,
    lineHeight: 42,
    letterSpacing: -0.8,
    textAlign: 'center',
  },
  message: {
    color: '#825f55',
    fontSize: 16,
    lineHeight: 24,
    textAlign: 'center',
    marginTop: 10,
  },
  actionArea: {
    minHeight: 76,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 26,
  },
  button: {
    minHeight: 58,
    maxWidth: 390,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    borderRadius: 20,
    paddingHorizontal: 22,
    paddingVertical: 15,
    backgroundColor: '#50342f',
    shadowColor: '#50342f',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.2,
    shadowRadius: 10,
    elevation: 5,
  },
  buttonText: {
    flexShrink: 1,
    color: '#fff',
    fontWeight: '900',
    fontSize: 16,
    lineHeight: 22,
    textAlign: 'center',
  },
  buttonArrow: {
    color: '#ffd8c5',
    fontWeight: '900',
    fontSize: 22,
    lineHeight: 26,
  },
  movieIndicator: {
    flexDirection: 'row',
    gap: 8,
    padding: 16,
  },
  movieDot: {
    width: 9,
    height: 9,
    borderRadius: 5,
    backgroundColor: '#c56f64',
  },
  movieDotMuted: {
    opacity: 0.55,
  },
  movieDotFaint: {
    opacity: 0.25,
  },
});
