import { StyleSheet } from 'react-native';

import { RememberCatColors, RememberCatFonts } from '@/constants/theme';

export const styles = StyleSheet.create({
  backdrop: {
    flex: 1,
    backgroundColor: RememberCatColors.scrim,
    justifyContent: 'center',
    paddingHorizontal: 22,
  },
  card: {
    backgroundColor: RememberCatColors.card,
    borderRadius: 28,
    padding: 24,
    shadowColor: RememberCatColors.shadow,
    shadowOpacity: 0.22,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 9,
    maxHeight: '92%',
  },
  scrollContent: { paddingBottom: 2 },
  header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  kicker: {
    color: RememberCatColors.primary,
    fontFamily: RememberCatFonts.bodyExtraBold,
    letterSpacing: 1.3,
    fontSize: 10,
  },
  title: {
    color: RememberCatColors.foreground,
    fontFamily: RememberCatFonts.displaySemiBold,
    fontSize: 25,
    marginTop: 3,
  },
  close: { color: RememberCatColors.mutedForeground, fontSize: 29 },
  description: {
    color: RememberCatColors.mutedForeground,
    fontFamily: RememberCatFonts.body,
    fontSize: 14,
    lineHeight: 20,
    marginTop: 14,
    marginBottom: 14,
  },
  inputFrame: {
    borderRadius: 14,
    backgroundColor: RememberCatColors.inputBackground,
    borderWidth: 2,
    overflow: 'hidden',
  },
  inputFrameNeutral: { borderColor: RememberCatColors.border },
  inputFrameError: { borderColor: RememberCatColors.destructive },
  inputFrameWarning: { borderColor: '#c88719' },
  inputFrameReady: { borderColor: RememberCatColors.success },
  feedback: { paddingHorizontal: 13, paddingTop: 11, paddingBottom: 9 },
  feedbackNeutral: { backgroundColor: RememberCatColors.muted },
  feedbackError: { backgroundColor: RememberCatColors.destructiveBackground },
  feedbackWarning: { backgroundColor: '#fff3d6' },
  feedbackReady: { backgroundColor: RememberCatColors.successBackground },
  feedbackHeading: { flexDirection: 'row', alignItems: 'flex-start', gap: 8 },
  statusIcon: {
    width: 20,
    height: 20,
    borderRadius: 10,
    overflow: 'hidden',
    textAlign: 'center',
    fontFamily: RememberCatFonts.bodyExtraBold,
    fontSize: 13,
    lineHeight: 20,
  },
  statusIconNeutral: {
    backgroundColor: RememberCatColors.border,
    color: RememberCatColors.foreground,
  },
  statusIconError: {
    backgroundColor: RememberCatColors.destructive,
    color: RememberCatColors.primaryForeground,
  },
  statusIconWarning: { backgroundColor: '#c88719', color: '#fffdf8' },
  statusIconReady: {
    backgroundColor: RememberCatColors.success,
    color: RememberCatColors.successForeground,
  },
  statusMessage: {
    flex: 1,
    color: RememberCatColors.foreground,
    fontFamily: RememberCatFonts.bodyBold,
    fontSize: 14,
    lineHeight: 20,
  },
  reviewNotice: {
    borderRadius: 10,
    backgroundColor: '#fff3d6',
    color: '#8b5700',
    fontFamily: RememberCatFonts.bodyBold,
    fontSize: 12,
    lineHeight: 17,
    marginTop: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  input: {
    minHeight: 145,
    padding: 14,
    paddingTop: 12,
    color: RememberCatColors.foreground,
    fontFamily: RememberCatFonts.body,
    fontSize: 15,
  },
  saveButton: {
    height: 57,
    borderRadius: 18,
    backgroundColor: RememberCatColors.primary,
    marginTop: 17,
    alignItems: 'center',
    justifyContent: 'center',
  },
  saveButtonDisabled: { opacity: 0.42 },
  saveText: {
    color: RememberCatColors.primaryForeground,
    fontFamily: RememberCatFonts.bodyExtraBold,
    fontSize: 16,
  },
  saveArrow: {
    position: 'absolute',
    right: 19,
    color: RememberCatColors.primaryForeground,
    fontSize: 22,
  },
});
