import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  overlay: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingTop: 72,
  },
  celebration: {
    minWidth: 214,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 24,
    borderWidth: 2,
    borderColor: '#70be84',
    backgroundColor: '#fff',
    paddingHorizontal: 18,
    paddingVertical: 12,
    shadowColor: '#2d7d42',
    shadowOffset: { width: 0, height: 7 },
    shadowOpacity: 0.25,
    shadowRadius: 12,
    elevation: 8,
  },
  sparkles: {
    position: 'absolute',
    top: -22,
    color: '#e5a125',
    fontSize: 20,
    lineHeight: 28,
  },
  catBubble: {
    width: 76,
    height: 64,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 19,
    borderWidth: 2,
    borderColor: '#a4d8b0',
    backgroundColor: '#ebf9ee',
  },
  cat: {
    fontSize: 40,
    lineHeight: 50,
  },
  thumb: {
    fontSize: 23,
    lineHeight: 29,
    marginLeft: -8,
    marginTop: -13,
  },
  label: {
    color: '#2f8848',
    fontWeight: '900',
    fontSize: 22,
    lineHeight: 28,
    marginLeft: 13,
  },
});
