import { StyleSheet } from 'react-native';

import { RememberCatColors, RememberCatFonts } from '@/constants/theme';

export const styles = StyleSheet.create({
  content: { flex: 1, paddingHorizontal: 20 },
  top: { height: 58, flexDirection: 'row', alignItems: 'center', gap: 12 },
  closeButton: {
    minWidth: 32,
    minHeight: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  close: { fontSize: 30, lineHeight: 36, color: RememberCatColors.mutedForeground },
  progressTrack: {
    height: 8,
    flex: 1,
    overflow: 'hidden',
    borderRadius: 5,
    backgroundColor: RememberCatColors.muted,
  },
  progressFill: { height: '100%', borderRadius: 5, backgroundColor: RememberCatColors.primary },
  progressLabel: {
    color: RememberCatColors.mutedForeground,
    fontFamily: RememberCatFonts.bodyExtraBold,
    fontSize: 12,
  },
  heading: { marginTop: 18, marginBottom: 20 },
  kicker: {
    color: RememberCatColors.primary,
    fontFamily: RememberCatFonts.bodyExtraBold,
    letterSpacing: 1.1,
    fontSize: 11,
  },
  title: {
    color: RememberCatColors.foreground,
    fontFamily: RememberCatFonts.displaySemiBold,
    fontSize: 29,
    lineHeight: 37,
    letterSpacing: -1,
    marginTop: 5,
  },
  hint: {
    color: RememberCatColors.mutedForeground,
    fontFamily: RememberCatFonts.body,
    fontSize: 14,
    lineHeight: 20,
    marginTop: 6,
  },
  board: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 12 },
  promptColumn: { flex: 1 },
  promptCard: {
    minHeight: 112,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 20,
    borderWidth: 2,
    borderColor: RememberCatColors.primaryBorder,
    backgroundColor: RememberCatColors.selectedBackground,
    paddingHorizontal: 12,
  },
  promptLabel: {
    color: RememberCatColors.primary,
    fontFamily: RememberCatFonts.bodyExtraBold,
    fontSize: 10,
    lineHeight: 14,
    fontWeight: '900',
    letterSpacing: 1,
  },
  promptWord: {
    color: RememberCatColors.foreground,
    fontFamily: RememberCatFonts.displaySemiBold,
    fontSize: 22,
    lineHeight: 28,
    fontWeight: '900',
    textAlign: 'center',
    marginTop: 8,
  },
  repetitionPill: {
    alignItems: 'center',
    borderRadius: 14,
    backgroundColor: RememberCatColors.successBackground,
    marginTop: 10,
    paddingVertical: 8,
    paddingHorizontal: 9,
  },
  repetitionText: {
    color: RememberCatColors.success,
    fontFamily: RememberCatFonts.bodyExtraBold,
    fontSize: 11,
    lineHeight: 15,
  },
  answerColumn: { flex: 1, gap: 10 },
  answer: {
    minHeight: 62,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 17,
    borderWidth: 1,
    borderColor: RememberCatColors.border,
    backgroundColor: RememberCatColors.card,
    paddingHorizontal: 10,
  },
  answerSelected: {
    borderWidth: 2,
    borderColor: RememberCatColors.primary,
    backgroundColor: RememberCatColors.selectedBackground,
  },
  answerCorrect: {
    borderWidth: 2,
    borderColor: RememberCatColors.success,
    backgroundColor: RememberCatColors.successBackground,
  },
  answerIncorrect: {
    borderWidth: 2,
    borderColor: RememberCatColors.destructive,
    backgroundColor: RememberCatColors.destructiveBackground,
  },
  answerPressed: { opacity: 0.72, transform: [{ scale: 0.98 }] },
  answerText: {
    color: RememberCatColors.foreground,
    fontFamily: RememberCatFonts.bodyExtraBold,
    fontSize: 14,
    lineHeight: 19,
    fontWeight: '800',
    textAlign: 'center',
  },
});
