import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  content: { flex: 1, paddingHorizontal: 20 },
  top: { height: 58, flexDirection: 'row', alignItems: 'center', gap: 12 },
  closeButton: {
    minWidth: 32,
    minHeight: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  close: { fontSize: 30, lineHeight: 36, color: '#9a776c' },
  progressTrack: {
    height: 8,
    flex: 1,
    overflow: 'hidden',
    borderRadius: 5,
    backgroundColor: '#efdcd1',
  },
  progressFill: { height: '100%', borderRadius: 5, backgroundColor: '#d77c70' },
  progressLabel: { color: '#9a776c', fontWeight: '800', fontSize: 12 },
  heading: { marginTop: 18, marginBottom: 20 },
  kicker: {
    color: '#d17c70',
    fontWeight: '800',
    letterSpacing: 1.1,
    fontSize: 11,
  },
  title: {
    color: '#50342f',
    fontWeight: '800',
    fontSize: 29,
    lineHeight: 37,
    letterSpacing: -1,
    marginTop: 5,
  },
  hint: { color: '#916e63', fontSize: 14, lineHeight: 20, marginTop: 6 },
  board: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 12 },
  promptColumn: { flex: 1 },
  promptCard: {
    minHeight: 112,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 20,
    borderWidth: 2,
    borderColor: '#dc9889',
    backgroundColor: '#fff0e4',
    paddingHorizontal: 12,
  },
  promptLabel: {
    color: '#b36e60',
    fontSize: 10,
    lineHeight: 14,
    fontWeight: '900',
    letterSpacing: 1,
  },
  promptWord: {
    color: '#553832',
    fontSize: 22,
    lineHeight: 28,
    fontWeight: '900',
    textAlign: 'center',
    marginTop: 8,
  },
  repetitionPill: {
    alignItems: 'center',
    borderRadius: 14,
    backgroundColor: '#e7f6f2',
    marginTop: 10,
    paddingVertical: 8,
    paddingHorizontal: 9,
  },
  repetitionText: { color: '#397b6d', fontSize: 11, lineHeight: 15, fontWeight: '900' },
  answerColumn: { flex: 1, gap: 10 },
  answer: {
    minHeight: 62,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 17,
    borderWidth: 1,
    borderColor: '#ead7cd',
    backgroundColor: '#ffffff',
    paddingHorizontal: 10,
  },
  answerSelected: { borderWidth: 2, borderColor: '#d77c70', backgroundColor: '#fff0e8' },
  answerCorrect: { borderWidth: 2, borderColor: '#73ad9e', backgroundColor: '#e3f5ef' },
  answerIncorrect: { borderWidth: 2, borderColor: '#d8756d', backgroundColor: '#fce8e5' },
  answerPressed: { opacity: 0.72, transform: [{ scale: 0.98 }] },
  answerText: {
    color: '#583b35',
    fontSize: 14,
    lineHeight: 19,
    fontWeight: '800',
    textAlign: 'center',
  },
});
